#!/usr/bin/env python3
import cv2
import argparse
from numpy import concatenate
parser = argparse.ArgumentParser(description='Concatinate Two Images')
parser.add_argument('input', type=str, nargs=2, 
    help='Path to images for contaticnation. The images must have the same dimensions on the axis that is being combindes')
parser.add_argument('output', type=str, nargs=1, help="Output file")
args = parser.parse_args()
img1_path = args.input[0]
img2_path = args.input[1]
out_path = args.output[0]
img1 = cv2.imread(img1_path, 0)
img2 = cv2.imread(img2_path, 0)
combined = concatenate((img1, img2), axis=0)
cv2.imwrite(out_path, combined)